services:
  campus-db:
    image: mariadb:10.4
    container_name: smartcampus_mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  activemq:
    image: apache/activemq-classic:latest
    container_name: smartcampus_activemq
    restart: always
    ports:
      - "61616:61616" # The connection port defined in application.properties
      - "8161:8161"   # The Admin Web Console
    environment:
      - ACTIVEMQ_ADMIN_PASSWORD=admin
      - ACTIVEMQ_USER_PASSWORD=admin

volumes:
  db_data: